version: "3.9"
services:
  db:
    image: postgres:17
    container_name: karyasetu_postgres
    restart: always
    environment:
      POSTGRES_USER: karyasetu
      POSTGRES_PASSWORD: karyasetu4036
      POSTGRES_DB: karyasetu_db
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  app:
    build: .
    container_name: nextjs_app
    restart: always
    environment:
      DATABASE_URL: postgresql://karyasetu:karyasetu4036@db:5432/karyasetu_db
    ports:
      - "3000:3000"
    depends_on:
      - db
    command: >
      sh -c "npx prisma migrate deploy && npm start"

volumes:
  db_data:
